title: Shiping Zhong's Homepage
page-top-title: Shiping Zhong
top-section-bg-text: 自由而简单
home-subtitle: 钟世平
hobbies-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;兴趣爱好'
awards-subtitle: '<i class="bi bi-award-fill"></i>荣誉与获奖'
nav-home: 首页
nav-hobbies: 爱好
nav-awards: 奖项
nav-menu: 菜单
github-link: Github
license-link: License
contact-link: 给俺打赏
copyright-text: '&copy; Shiping Zhong 2023-2025. All Rights Reserved.'