title: 钟世平的主页
page-top-title: 钟世平
top-section-bg-text: 自由与简单
home-subtitle: 钟世平
hobbies-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;兴趣爱好'
awards-subtitle: '<i class="bi bi-award-fill"></i>荣誉与获奖'
nav-home: 首页
nav-hobbies: 爱好
nav-awards: 奖项
nav-menu: 菜单
github-link: Github
license-link: 许可
contact-link: 赞助我们
copyright-text: '&copy; 钟世平 2023-2025. 保留所有权利.'