title: Shiping Zhong's Homepage
page-top-title: Shiping Zhong
top-section-bg-text: Free & Simple
home-subtitle: Shiping Zhong&ensp;|&ensp;钟世平
hobbies-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;HOBBIES'
awards-subtitle: '<i class="bi bi-award-fill"></i>AWARDS'
nav-home: HOME
nav-hobbies: HOBBIES
nav-awards: AWARDS
nav-menu: MENU
github-link: Github
license-link: License
contact-link: Sponsor us
copyright-text: '&copy; Shiping Zhong 2023-2025. All Rights Reserved.'
