title: Shiping Zhong's Homepage
page-top-title: Shiping Zhong
top-section-bg-text: Free & Simple
home-subtitle: Shiping Zhong&ensp;|&ensp;钟世平
copyright-text: '&copy; Shiping Zhong 2023-2025. All Rights Reserved.'
